<a href="https://colab.research.google.com/github/ShaimaM/Python/blob/main/Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

3x + 5y = 6


7x - 5y = 9

In [ ]:
a = np.array([[3,5], [7,-5]])
b = np.array([6,9])
x = np.linalg.solve(a, b)
x

array([1.5, 0.3])

x + y + z = 6


y + z = -4


2x + 5y - z = 27

In [ ]:
a = np.array([[1,1,1],[0,1,1],[2,5,-1]])
b = np.array([6,-4,27])
x = np.linalg.solve(a, b)
x

array([10. ,  0.5, -4.5])

x + y = 4


2x + 2y = 8

In [ ]:
a = np.array([[1,1],[2,2]])
b = np.array([4,8])
x = np.linalg.solve(a, b)
x

LinAlgError: ignored

**A singular matrix is one that is not invertible. This means that the system of equations you are trying to solve does not have a unique solution; linalg.solve can't handle this.**

[Refrence](https://stackoverflow.com/questions/13795682/numpy-error-singular-matrix#:~:text=A%20singular%20matrix%20is%20one,solve%20can't%20handle%20this.)




In [ ]:
a = np.array([[1,1],[2,2]])
b = np.array([4,8])
x = np.linalg.lstsq(a, b)
x


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([2., 2.]),
 array([], dtype=float64),
 1,
 array([3.16227766e+00, 8.22677308e-17]))